# HTTP Methods

Method   | Description
-------- | -----------
`GET`    | Fetch - retrieve resources
`POST`   | Create - create new resources
`PATCH`  | Update - (partially) modify existing resources
`DELETE` | Delete - remove resources
