# Questions?

If you have any questions you can:
- Join our [Discord server][discord] (recommended)
- Ping [@wopian][wopian], [@matthewdias][matthewdias] or [@nuck][nuck] on Kitsu.

[jsonapi]:http://jsonapi.org/format/
[jsonapi-client]:http://jsonapi.org/implementations/#client-libraries
[wopian]:https://kitsu.io/users/wopian
[matthewdias]:https://kitsu.io/users/matthewdias
[nuck]:https://kitsu.io/users/nuck
[discord]:https://invite.gg/kitsu
