# Status Codes

Code  | Description
----- | -----------
`200` | OK - request succeeded (GET, PATCH, DELETE)
`201` | Created - new resource created (POST)
`204` | No Content - request succeeded (DELETE)
`400` | Bad Request - malformed request
`401` | Unauthorized - invalid or no authentication details provided
`404` | Not Found - resource does not exist
`406` | Not Acceptable - invalid `Accept` header
`5xx` | Server Error
