## Library Entry Logs [/library-entry-logs/{id}]

+ Parameters
    + id (number, `221679`) - ID of the library entry log resource

+ Attributes (libraryEntryLogsAttributes)

### GET List [GET /library-entry-logs]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (libraryEntryLogs)
        + meta (object, required)
            + count: 6409 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/library-entry-logs?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/library-entry-logs?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/library-entry-logs?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/library-entry-logs?page%5Blimit%5D=10&page%5Boffset%5D=6399` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (libraryEntryLogs)

+ Response 404 (application/vnd.api+json)
    + Attributes (error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)
