## Library Entries [/library-entries/{id}]

**Access Requirements**

Authenticated | Role | GET | POST | PATCH | DELETE
------------: | ---: | :-: | :--: | :---: | :----:
No            |️ None | Y*  | N    | N     | N
Yes           | None | Y*† | Y    | Y     | Y

\* Resources with `private: true` are not accessible, unless
authenticated as the user associated with the library entry

† Adult content will only be shown if enabled in the authenticated
user's settings

**Filters**

Filters can be used in `snake_case` or `camelCase` format

Filter       | Example                                  | Notes
-----------: | ---------------------------------------: | :----
`anime_id`   | `1`, `43,2,300`                          |
`drama_id`   |                                          |
`following`  |                                          |
`kind`       | `anime`, `anime,manga`                   | Filter by the related media type
`manga_id`   | `2`, `8,987`                             |
`media_id`   |                                          | **DEPRECATED** - use `anime_id`, `manga_id` or `drama_id`
`media_type` | `anime`, `anime,manga`                   | **DEPRECATED** - use `kind`
`since`      | `2017-01-28`, `2013-03-25T00:00:00.000Z` | Returns entries updated since the supplied ISO 8601 date
`status`     | `current`, `onHold`                      | Values of the `status` attribute
`user_id`    | `42603`, `2,7`                           |

+ Parameters
    + id (number, `1`) - ID of the library entry resource

+ Attributes (libraryEntriesAttributes)

### Fetch Collection [GET /library-entries]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (libraryEntriesLinks)
        + meta (object, required)
            + count: 0 (number, required)
        + link (object)
            + first: `https://kitsu.io/api/edge/library-entries?page%5Blimit%5D=10&page%5Boffset%5D=0
            + prev: `https://kitsu.io/api/edge/library-entries?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/library-entries?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/library-entries?page%5Blimit%5D=10&page%5Boffset%5D=0

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (libraryEntriesLinks)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Create Resource [POST]

+ Request (application/vnd.api+json)
    + Attributes (libraryEntriesRequest)

+ Response 201 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Update Resource [PATCH]

+ Request (application/vnd.api+json)
    + Attributes (libraryEntriesRequest)

+ Response 200 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Delete Resource [DELETE]

+ Request (application/vnd.api+json)
    + Attributes (libraryEntries)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
