FORMAT: 1A
HOST: https://kitsu.io/api/edge

# Kitsu API

Kitsu is a modern anime discovery platform that helps you track the
anime you're watching, discover new anime and socialize with other
fans.

With the Kitsu API you can do everything the client can do and much
more.

# JSON API

The Kitsu API implements the JSON API specification. This means
there are some notable semantics to how you consume it, but
understanding it will take a lot of the work of using it out of your
hands.

These docs will include a short overview of the capabilities, but
you can consult the [JSON API Specification][jsonapi] for more
information.

You can be more specific about the data you want to retrieve by
using URL parameters and are outlined below.

**Note:** This documentation will display parameters with brackets
(`[` and `]`) for readability, but actual URLs will need to be
percent-encoded (`%5B` and `%5D`).

## Request Headers

As per the JSON API specification, all requests to the API should
contain these headers:

```
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
```

## Filtering and Search

Filtering lets you query data that contains certain matching
attributes or relationships. These take the form of
`filter[attribute]=value`. For example, you can request all the
anime of the Adventure genre:

```
/anime?filter[genres]=adventure
```

For some models, you can also search based on the query text:

```
/anime?filter[text]=cowboy%20bebop
```

## Pagination

You can choose how much of a resource to receive by specifying
pagination parameters. Pagination is supported via `limit` and
`offset`. Resources are paginated in groups of `20` by default.

`/anime?page[limit]=5&page[offset]=0`

The response will include URLs for the first, next and last page of
resources in the `links` object based on your request.

```
"links": {
    "first": "https://kitsu.io/api/edge/anime?page[limit]=5&page[offset]=0",
    "next": "https://kitsu.io/api/edge/anime?page[limit]=5&page[offset]=5",
    "last": "https://kitsu.io/api/edge/anime?page[limit]=5&page[offset]=12062"
}
```

## Sorting

Sorting by attributes is also supported. By default, sorts are
applied in ascending order. You can request a descending order by
prepending `-` to the parameter. You can use a comma-delimited list
to sort by multiple attributes.

`/users?sort=-followersCount,-followingCount`

## Includes

You can include related resources with `include=[relationship]`.
You can also specify successive relationships using a `.`. A
comma-delimited list can be used to request multiple relationships.

`/library-entries?include=user,anime.genres`

## Sparse Fieldsets

You can request a resource to only return a specific set of fields
in its response. For example, to only receive a user's name and
creation date:

`/users?fields[users]=name,createdAt`

## Client Implementations

JSON API has a great advantage in that since its standardised,
API-agnostic tools can be made to abstract away the semantics of
consuming and working with the data. It is recommended that you use
a JSON API client to implement the Kitsu API for this reason.

Many implementations in over 13 languages can be found on the
[JSON API website][jsonapi-client].

# Response Codes

Code  | Description
----- | -----------
`200` | Success - request has succeeded
`201` | Success - new resource created
`400` | Bad Request - malformed request syntax
`401` | Unauthorized - request lacks valid authentication credentials
`404` | Not Found - resource does not exist
`5xx` | Server Error

# Versioning

Every year, we release a new version of the API, numbered by the
last two digits of the current year. For example, the root URL of
this (the 2017) release is `https://kitsu.io/api/17/`.

No fields, endpoints, or resources will be removed until the next
year's release, but may be changed to return empty values (arrays,
empty strings, etc.) before then. Fields, endpoints, and resources
may be added throughout the lifetime of a release.

In addition to these versioned APIs, there is access to the same API
our website uses. However, this offers no guarantees: anything could
change at any time. We suggest you don't use this, but if you need
to, it can be accessed at `https://kitsu.io/api/edge/`.

## Life Cycle

Upon release of a new version, the previous version will be
maintained for one year or until usage drops below 2% of API
traffic.

During this period, it will not be updated to have any new fields,
endpoints, or resources. You are expected to keep your applications
running on the latest version of the API. For most applications,
upgrading should take no more than a few hours of work.

# Questions?

If you have any questions, you can join our Slack by sending an
email to josh@kitsu.io or pinging [@wopian][wopian],
[@matthewdias][matthewdias] or [@nuck][nuck] on Kitsu.

[jsonapi]:http://jsonapi.org/format/
[jsonapi-client]:http://jsonapi.org/implementations/#client-libraries
[wopian]:https://kitsu.io/users/wopian
[matthewdias]:https://kitsu.io/users/matthewdias
[nuck]:https://kitsu.io/users/nuck

# Group Authentication

Kitsu uses OAuth 2 for authentication. It is not required to send
authenticated requests for most endpoints.

After registering your app, you will receieve a client ID and a
client secret. The client ID is considered public information and is
used to build login URLs or included in source code. The client
secret **must** be kept confidential.

**NOTE:** Application registration has not yet been implemented, so
for now all requests should be  made with the following client ID
and client secret:

```
CLIENT_ID: dd031b32d2f56c990b1425efe6c42ad847e7fe3ab46bf1299f05ecd856bdb7dd
CLIENT_SECRET: 54d7307928f63414defd96399fc31ba847961ceaecef3a5fd93144e960c0e151
```

# Grant Types

OAuth 2 provides several grant types for different use cases. The
grant types defined are:

- **Authorization Code** for apps running on a web server,
browser-based and mobile apps
- **Password** for logging in with a username and Password
- **Client Credentials** for application access
# Group Characters & People

## Anime Characters [/anime-characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime character resource

+ Attributes (animeCharactersAttributes)

### GET List [GET /anime-characters]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeCharacters)
        + meta (object)
            + count: 109379 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=109369`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeCharacters)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Anime Productions [/anime-productions/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime production resource

+ Attributes (animeProductionsAttributes)

### GET List [GET /anime-productions]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeProductions)
        + meta (object)
            + count: 28401 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=28391`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeProductions)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Anime Staff [/anime-staff/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime staff resource

+ Attributes (animeStaffAttributes)

### GET List [GET /anime-staff]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeStaff)
        + meta (object)
            + count: 88543 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=88533`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeStaff)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Castings [/castings/{id}]

+ Parameters
    + id (number, `1`) - ID of the casting resource

+ Attributes (castingsAttributes)

### GET List [GET /castings]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (castings)
        + meta (object)
            + count: 244549 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=244539`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (castings)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Characters [/characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the character resource

+ Attributes (charactersAttributes)

### GET List [GET /characters]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (characters)
        + meta (object)
            + count: 95009 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=94999`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (characters)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Manga Characters [/manga-characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the manga character resource

+ Attributes (mangaCharactersAttributes)

### GET List [GET /manga-characters]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (mangaCharacters)
        + meta (object)
            + count: 0 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/manga-characters?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + last: `https://kitsu.io/api/edge/manga-characters?page%5Blimit%5D=10&page%5Boffset%5D=0`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (mangaCharacters)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Manga Staff [/manga-staff/{id}]

+ Parameters
    + id (number, `1`) - ID of the manga staff resource

+ Attributes (mangaStaffAttributes)

### GET List [GET /manga-staff]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (mangaStaff)
        + meta (object)
            + count: 1 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + last: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=0`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (mangaStaff)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## People [/people/{id}]

+ Parameters
    + id (number, `1`) - ID of the person resource

+ Attributes (peopleAttributes)

### GET List [GET /people]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (people)
        + meta (object)
            + count: 27957 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=27947`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (people)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Producers [/producers/{id}]

+ Parameters
    + id (number, `1`) - ID of the producer resource

+ Attributes (producersAttributes)

### GET List [GET /producers]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (producers)
        + meta (object)
            + count: 1333 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/producers?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/producers?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/producers?page%5Blimit%5D=10&page%5Boffset%5D=1323`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (producers)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
# Group Groups

## Group Categories [/group-categories/{id}]

+ Parameters
    + id (number, `1`) - ID of the group category resource
## Group Members [/group-members/{id}]

+ Parameters
    + id (number, `1`) - ID of the group members resource
## Group Neighbors [/group-neighbors/{id}]

+ Parameters
    + id (number, `1`) - ID of the group neighbors resource
## Groups [/groups/{id}]

+ Parameters
    + id (number, `1`) - ID of the group resource
# Group Media

## Anime [/anime/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime resource

+ Attributes (animeAttributes)

### GET List [GET /anime]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (anime)
        + meta (object)
            + count: 12080 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime?page%5Blimit%5D=10&page%5Boffset%5D=12070`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (anime)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Categories [/categories/{id}]

+ Parameters
    + id (number, `1`) - ID of the category resource

+ Attributes (categoriesAttributes)

### GET List [GET /categories]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (categoriesAttributes)
        + meta (object)
            + count: 228 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=218`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (categoriesAttributes)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400



## Franchises [/franchises/{id}]

+ Parameters
    + id (number, `1`) - ID of the franchise resource

+ Attributes (franchisesAttributes)

### GET List [GET /franchises]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (franchises)
        + meta (object)
            + count: 1332 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/franchises?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/franchises?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/franchises?page%5Blimit%5D=10&page%5Boffset%5D=1322`
  

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (franchises)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
## Genres [/genres/{id}]

+ Parameters
    + id (number, `1`) - ID of the genre resource

+ Attributes (genresAttributes)

### GET List [GET /genres]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (genres)
        + meta (object)
            + count: 61 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=51`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (genres)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400


## Mappings [/mappings/{id}]

+ Parameters
    + id (number, `1`) - ID of the mapping resource

+ Attributes (mappingsAttributes)

### GET List [GET /mappings]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (mappings)
        + meta (object)
            + count: 109379 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/mappings?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/mappings?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/mappings?page%5Blimit%5D=10&page%5Boffset%5D=109369`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (mappings)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400



# Group Posts

## Comment Likes [/comment-likes/{id}]

+ Parameters
    + id (number, `1`) - ID of the comment like resource
## Comments [/comments/{id}]

+ Parameters
    + id (number, `1`) - ID of the comment resource
## Post Likes [/post-likes/{id}]

+ Parameters
    + id (number, `1`) - ID of the post like resource
## Posts [/posts/{id}]

+ Parameters
    + id (number, `1`) - ID of the post resource
# Group Reviews

## Review Likes [/review-likes/{id}]

+ Parameters
    + id (number, `1`) - ID of the review like resource
## Reviews [/reviews/{id}]

+ Parameters
    + id (number, `1`) - ID of the review resource
# Site Announcements [/site-announcements/{id}]

+ Parameters
    + id (number, `1`) - ID of the site announcement resource
# Group Users











# Data Structures

## animeCharactersAttributes (object)
+ role: main - Role the character plays in the anime

## animeCharacters (object)
+ id: 1 (required)
+ type: animeCharacters (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/anime-characters/1` (required)
+ attributes (animeCharactersAttributes)
+ relationships (object)
    + anime (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime-characters/1/relationships/anime`
            + related: `https://kitsu.io/api/edge/anime-characters/1/anime`
    + character (object)
            + self: `https://kitsu.io/api/edge/anime-characters/1/relationships/character`
            + related: `https://kitsu.io/api/edge/anime-characters/1/character`
    + castings (object)
            + self: `https://kitsu.io/api/edge/anime-characters/1/relationships/castings`
            + related: `https://kitsu.io/api/edge/anime-characters/1/castings`
## animeProductionsAttributes (object)
+ role: producer

## animeProductions (object)
+ id: 1 (required)
+ type: animeProductions (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/anime-productions/1` (required)
+ attributes (animeCharactersAttributes)
+ relationships (object)
    + anime (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime-productions/1/relationships/anime`
            + related: `https://kitsu.io/api/edge/anime-productions/1/anime`
    + producer (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime-productions/1/relationships/producer`
            + related: `https://kitsu.io/api/edge/anime-productions/1/producer`
## animeStaffAttributes (object)
+ role: producer

## animeStaff (object)
+ id: 1 (required)
+ type: animeStaff (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/anime-staff/1` (required)
+ attributes (animeStaffAttributes)
+ relationships (object)
    + anime (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime-staff/1/relationships/anime`
            + related: `https://kitsu.io/api/edge/anime-staff/1/anime`
    + person (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime-staff/1/relationships/person`
            + related: `https://kitsu.io/api/edge/anime-staff/1/person`
## castingsAttributes (object)
+ role: producer
+ voiceActor: false (boolean)
+ featured: false (boolean)
+ language: English

## castings (object)
+ id: 1 (required)
+ type: castings (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/castings/1` (required)
+ attributes (castingsAttributes)
+ relationships (object)
    + media (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/castings/1/relationships/media`
            + related: `https://kitsu.io/api/edge/castings/1/media`
    + character (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/castings/1/relationships/character`
            + related: `https://kitsu.io/api/edge/castings/1/character`
    + person (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/castings/1/relationships/person`
            + related: `https://kitsu.io/api/edge/castings/1/person`
## charactersAttributes (object)
+ slug: jet-black
+ name: Jet Black
+ malId: 3 (number)
+ description: `Jet, known on his home satellite as the \"Black Dog\"...`
+ image (object)
    + original: `https://media.kitsu.io/characters/images/1/original.jpg?1483096805`

## characters (object)
+ id: 1 (required)
+ type: characters (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/characters/1` (required)
+ attributes (charactersAttributes)
+ relationships (object)
    + primaryMedia (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/characters/1/relationships/primary-media`
            + related: `https://kitsu.io/api/edge/characters/1/primary-media`
    + castings (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/characters/1/relationships/castings`
            + related: `https://kitsu.io/api/edge/characters/1/castings`
## mangaCharactersAttributes (object)

## mangaCharacters (object)
## mangaStaffAttributes (object)
+ role: producer

## mangaStaff (object)
+ id: 1 (required)
+ type: mangaStaff (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/manga-staff/1` (required)
+ attributes (mangaStaffAttributes)
+ relationships (object)
    + manga (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/manga-staff/1/relationships/manga`
            + related: `https://kitsu.io/api/edge/manga-staff/1/manga`
    + person (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/manga-staff/1/relationships/person`
            + related: `https://kitsu.io/api/edge/manga-staff/1/person`
## peopleAttributes (object)
+ image: `https://media.kitsu.io/people/images/1/original.jpg?1416260317`
+ name: Masahiko Minami
+ malId: 6519 (number)

## people (object)
+ id: 1 (required)
+ type: people (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/people/1` (required)
+ attributes (peopleAttributes)
+ relationships (object)
    + castings (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/people/1/relationships/castings`
            + related: `https://kitsu.io/api/edge/people/1/castings`
## producersAttributes (object)
+ slug: sunrise
+ name: Sunrise

## producers (object)
+ id: 1 (required)
+ type: producers (required)
+ links (object, required)
    + self: `https://kitsu.io/api/edge/producers/1` (required)
+ attributes (producersAttributes)
+ relationships (object)
    + animeProductions (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/producers/1/relationships/anime-productions`
            + related: `https://kitsu.io/api/edge/producers/1/anime-productions`






## animeAttributes (object)
+ slug: `cowboy-bebop`
+ synopsis: `In the year 2071, humanity has colonoized several of the planets and moons...`
+ coverImageTopOffset: 400 (number)
+ titles (object)
    + en: Cowboy Bebop (nullable)
    + en_jp: Cowbop Bebop (nullable)
    + ja_jp: カウボーイビバップ (nullable)
+ canonicalTitle: Cowboy Bebop
+ abbreviatedTitles: COWBOY BEBOP (array)
+ averageRating: 88.65
+ ratingFrequencies (object)
    + 2: 72
    + 3: 0
    + 4: 292
    + 5: 0
    + 6: 67
    + 7: 0
    + 8: 162
    + 9: 0
    + 10: 254
    + 11: 2
    + 12: 1393
    + 13: 10
    + 14: 1498
    + 15: 15
    + 16: 3767
    + 17: 28
    + 18: 4392
    + 19: 40
    + 20: 13607
+ userCount: 40405 (number)
+ favoritesCount: 3277 (number)
+ startDate: 1998-04-03
+ endDate: 1999-04-04
+ popularityRank: 10 (number)
+ ratingRank: 10 (number)
+ ageRating: R
+ ageRatingGuide: `17+ (violence & profanity)`
+ subtype: TV
+ status: finished
+ posterImage (object)
    + tiny: `https://media.kitsu.io/anime/poster_images/1/tiny.jpg?1431697256`
    + small: `https://media.kitsu.io/anime/poster_images/1/small.jpg?1431697256`
    + medium: `https://media.kitsu.io/anime/poster_images/1/medium.jpg?1431697256`
    + large: `https://media.kitsu.io/anime/poster_images/1/large.jpg?1431697256`
    + original: `https://media.kitsu.io/anime/poster_images/1/original.jpg?1431697256`
+ coverImage (object)
    + tiny: `https://media.kitsu.io/anime/cover_images/1/tiny.jpg?1416336000`
    + small: `https://media.kitsu.io/anime/cover_images/1/small.jpg?1416336000`
    + large: `https://media.kitsu.io/anime/cover_images/1/large.jpg?1416336000`
    + original: `https://media.kitsu.io/anime/cover_images/1/original.jpg?1416336000`
+ episodeCount: 26 (number)
+ episodeLength: 24 (number)
+ youtubeVideoId: qig4KOK2R2g
+ showType: TV
+ nsfw: false (boolean)

## anime (object)
+ id: 1
+ type: anime
+ links (object)
    + self: `https://kitsu.io/api/edge/anime/1`
+ attributes (animeAttributes)
+ relationships (object)
    + genres (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/genres`
            + related: `https://kitsu.io/api/edge/anime/1/genres`
    + categories (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/categories`
            + related: `https://kitsu.io/api/edge/anime/1/categories`
    + castings (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/castings`
            + related: `https://kitsu.io/api/edge/anime/1/castings`
    + installments (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/installments`
            + related: `https://kitsu.io/api/edge/anime/1/installments`
    + mappings (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/mappings`
            + related: `https://kitsu.io/api/edge/anime/1/mappings`
    + reviews (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/reviews`
            + related: `https://kitsu.io/api/edge/anime/1/reviews`
    + mediaRelationships (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/media-relationships`
            + related: `https://kitsu.io/api/edge/anime/1/media-relationships`
    + episodes (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/episodes`
            + related: `https://kitsu.io/api/edge/anime/1/episodes`
    + streamingLinks (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/streaming-links`
            + related: `https://kitsu.io/api/edge/anime/1/streaming-links`
    + animeProductions (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/anime-productions`
            + related: `https://kitsu.io/api/edge/anime/1/anime-productions`
    + animeCharacters (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/anime-characters`
            + related: `https://kitsu.io/api/edge/anime/1/anime-characters`
    + animeStaff (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/anime/1/relationships/anime-staff`
            + related: `https://kitsu.io/api/edge/anime/1/anime-staff`
## categoriesAttributes (object)
+ title: Elf
+ description: `The origin of Elves (Norse; álfar(elves), álfr(elf)) can be found in ancient Norse mythology...`
+ totalMediaCount: 32 (number)
+ slug: elf
+ nsfw: false (boolean)
+ childCount: 0 (number)
+ image (object)
    + tiny: `https://media.kitsu.io/categories/images/10/tiny.jpg?1496212711`
    + small: `https://media.kitsu.io/categories/images/10/small.jpg?1496212711`
    + medium: `https://media.kitsu.io/categories/images/10/medium.jpg?1496212711`
    + large: `https://media.kitsu.io/categories/images/10/large.jpg?1496212711`
    + original: `https://media.kitsu.io/categories/images/10/original.jpg?1496212711`


## categories (object)
+ id: 10 (string, required)
+ type: categories (string, required) 
+ links (object)
    + self: `https://kitsu.io/api/edge/categories/10`
+ attributes (categoriesAttributes)
+ relationships (object)
    + parent (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/categories/10/relationships/parent`
            + related: `https://kitsu.io/api/edge/categories/10/parent`
    + anime (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/categories/10/relationships/anime`
            + related: `https://kitsu.io/api/edge/categories/10/anime`
    + drama (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/categories/10/relationships/drama`
            + related: `https://kitsu.io/api/edge/categories/10/drama`
    + manga (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/categories/10/relationships/manga`
            + related: `https://kitsu.io/api/edge/categories/10/manga`



## franchisesAttributes (object)
+ titles (object)
    + en: Darker than Black (nullable)
    + en_jp (nullable)
+ canonicalTitle

## franchises (object)
+ id: 1 (string, required)
+ type: franchises (string, required)
+ links (object)
    + self: `https://kitsu.io/api/edge/franchises/1`
+ attributes (franchisesAttributes)
+ relationships (object)
    + installments (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/franchises/1/relationships/installments`
            + related: `https://kitsu.io/api/edge/franchises/1/installments`
## genresAttributes (object)
+ name: Action
+ slug: action
+ description (nullable)

## genres (object)
+ id: 1 (string, required)
+ type: genres (string, required)
+ links (object)
    + self: `https://kitsu.io/api/edge/genres/1`
+ attributes (genresAttributes)


## mappingsAttributes (object)
+ externalSite: myanimelist/anime
+ externalId: 31608

## mappings (object)
+ id: 1 (string, required)
+ type: mappings (string, required)
+ links (object)
    + self: `https://kitsu.io/api/edge/mappings/1`
+ attributes (mappingsAttributes)
+ relationships (object)
    + media (object)
        + links (object)
            + self: `https://kitsu.io/api/edge/mappings/1/relationships/media`
            + related: `https://kitsu.io/api/edge/mappings/1/media`























