FORMAT: 1A
HOST: https://kitsu.io/api/edge

# Kitsu API

Kitsu is a modern anime discovery platform that helps you track the
anime you're watching, discover new anime and socialize with other
fans.

With the Kitsu API you can do everything the client can do and much
more.

:[Introduction](blueprint/introduction.apib)

:[Authentication](blueprint/authentication.apib)
:[Characters & People](blueprint/characters-people.apib)
:[Groups](blueprint/groups.apib)
:[Media](blueprint/media.apib)
:[Posts](blueprint/posts.apib)
:[Reviews](blueprint/reviews.apib)
:[Site Announcements](blueprint/site-announcements.apib)
:[Users](blueprint/users.apib)

:[Data Structures](blueprint/data-structures.apib)
