FORMAT: 1A
HOST: https://kitsu.io/api/edge

# Kitsu API

Kitsu is a modern anime discovery platform that helps you track the anime you're watching, discover new anime and socialize with other fans.

With the Kitsu API you can do everything the client can do and much more.

:[Introduction](introduction.apib)

:[Authentication](blueprint/authentication.apib)

:[Users](blueprint/users.apib)

:[Library](blueprint/library.apib)

:[Anime](blueprint/anime.apib)

:[Manga](blueprint/manga.apib)

:[Drama](blueprint/drama.apib)

:[People/Characters/Companies](blueprint/characters.apib)

:[Feeds](blueprint/feeds.apib)

:[Site Announcements](blueprint/announcements.apib)

:[Groups](blueprint/groups.apib)

:[Admin Panel](blueprint/admin.apib)

:[WebHooks](blueprint/webhooks.apib)
