## Reviews [/reviews/{id}]

**Status**: Deprecated. Use `media-reactions` instead.

**Authorisation**

Authenticated | Role      | GET | POST | PATCH | DELETE
------------: | --------: | :-: | :--: | :---: | :----:
No            | None      | Y   | N    | N     | N
Yes           | None      | Y   | Y    | Y     | Y
Yes           | Admin     | Y   | N    | Y     | Y

:[](../filters/HEADER)
:[](../filters/media-id)
:[](../filters/media-type)
:[](../filters/user-id)

+ Parameters
    + id (number, `4`) - ID of the review resource

+ Attributes (reviewsAttributes)

### Fetch Collection [GET /reviews]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (reviews)
        + meta (object, required)
            + count: 14802 (number, required)
        + links (object)
            + first: `https://kitsu.io/api/edge/reviews?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + prev: `https://kitsu.io/api/edge/reviews?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/reviews?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/reviews?page%5Blimit%5D=10&page%5Boffset%5D=14792`

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (reviews)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Create Resource [POST /reviews]

+ Request (application/vnd.api+json)

+ Response 201 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Update Resource [PATCH]

+ Request (application/vnd.api+json)

+ Response 200 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Delete Resource [DELETE]

+ Request (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
