## Category Favorites [/category-favorites/{id}]

**Authorisation**

Authenticated | Role      | GET | POST | PATCH | DELETE
------------: | --------: | :-: | :--: | :---: | :----:
No            | None      | Y   | N    | N     | N
Yes           | None      | Y   | Y    | Y     | Y
Yes           | Admin     | Y   | Y    | Y     | Y

:[](../filters/HEADER)
:[](../filters/user-id)
:[](../filters/category-id)

+ Parameters
    + id (number, `2`) - ID of the category favorite resource

### Fetch Collection [GET /category-favorites]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (categoryFavorites)
        + meta (object, required)
            + count: 3018 (number, required)
        + links (object)
            + first: `https://kitsu.io/api/edge/category-favorites?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + prev: `https://kitsu.io/api/edge/category-favorites?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/category-favorites?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/category-favorites?page%5Blimit%5D=10&page%5Boffset%5D=3008`

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (categoryFavorites)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Create Resource [POST /category-favorites]

+ Request (application/vnd.api+json)

+ Response 201 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Update Resource [PATCH]

+ Request (application/vnd.api+json)

+ Response 200 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Delete Resource [DELETE]

+ Request (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
