## Categories [/categories/{id}]

**Authorisation**

Authenticated | Role      | GET | POST | PATCH | DELETE
------------: | --------: | :-: | :--: | :---: | :----:
No            | None      | Y   | N    | N     | N
Yes           | None      | Y   | N    | N     | N
Yes           | Admin     | Y   | Y    | Y     | Y

:[](../filters/HEADER)
:[](../filters/parent-id)
:[](../filters/slug)
:[](../filters/nsfw)

**Pagination**
The maximum page limit is unlimited for this resource.

+ Parameters
    + id (number, `10`) - ID of the category resource

+ Attributes (categoriesAttributes)

### Fetch Collection [GET /categories]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (categories)
        + meta (object, required)
            + count: 229 (number, required)
        + links (object)
            + first: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + prev: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/categories?page%5Blimit%5D=10&page%5Boffset%5D=219`

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (categories)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
