## Genres [/genres/{id}]

+ Parameters
    + id (number, `1`) - ID of the genre resource

+ Attributes (genresAttributes)

### GET List [GET /genres]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (genres)
        + meta (object)
            + count: 61 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/genres?page%5Blimit%5D=10&page%5Boffset%5D=51`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (genres)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400