## Streaming Links [/streaming-links/{id}]

**Authorisation**

Authenticated | Role      | GET | POST | PATCH | DELETE
------------: | --------: | :-: | :--: | :---: | :----:
No            | None      | Y   | N    | N     | N
Yes           | None      | Y   | N    | N     | N
Yes           | Admin     | Y   | Y    | Y     | Y

:[](../filters/HEADER)

+ Parameters
    + id (number, `1`) - ID of the streaming link resource

+ Attributes (streamingLinksAttributes)

### Fetch Collection [GET /streaming-links]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (streamingLinks)
        + meta (object, required)
            + count: 2076 (number, required)
        + links (object)
            + first: `https://kitsu.io/api/edge/streaming-links?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + prev: `https://kitsu.io/api/edge/streaming-links?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/streaming-links?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/streaming-links?page%5Blimit%5D=10&page%5Boffset%5D=2066`

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (streamingLinks)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
