## Groups [/groups/{id}]

+ Parameters
    + id (number, `1`) - ID of the group resource

+ Attributes (groupsAttributes)

### Fetch Collection [GET /groups]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (groups)
        + meta (object, required)
            + count: 1917 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/groups?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/groups?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/groups?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/groups?page%5Blimit%5D=10&page%5Boffset%5D=1907` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (groups)

+ Response 404 (application/vnd.api+json)
    + Attributes (error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)
