## Group Tickets [/group-tickets/{id}]

**Authorisation**

Authenticated | Role      | GET | POST | PATCH | DELETE
------------: | --------: | :-: | :--: | :---: | :----:
No            | None      | N   | N    | N     | N
Yes           | None      | Y   | Y    | Y     | N
Yes           | Admin     | N   | N    | N     | N

:[](../filters/HEADER)
:[](../filters/group)
:[](../filters/user)
:[](../filters/assignee)
:[](../filters/status)
:[](../filters/query-group)
:[](../filters/query)

+ Parameters
    + id (number, `41`) - ID of the group ticket resource

+ Attributes (groupTicketsAttributes)

### Fetch Collection [GET /group-tickets]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (groupTickets)
        + meta (object, required)
            + count: 2 (number, required)
        + links (object)
            + first: `https://kitsu.io/api/edge/group-tickets?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + prev: `https://kitsu.io/api/edge/group-tickets?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/group-tickets?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/group-tickets?page%5Blimit%5D=10&page%5Boffset%5D=0`

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (groupTickets)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Create Resource [POST /group-tickets]

+ Request (application/vnd.api+json)

+ Response 201 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Update Resource [PATCH]

+ Request (application/vnd.api+json)

+ Response 200 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
