# Group Anime

# Single [/anime/{id}]

TBA

+ Parameters
    + id (number) - ID of the anime

## Fetch [GET]

+ Request
    + Headers

            :[](headers/jsonapi.apib)

+ Response 200 (application/vnd.api+json)

        :[](response/anime/get-one-200.json)

# List [/anime]

TBA

## Fetch [GET]

+ Request
    + Headers

            :[](headers/jsonapi.apib)

+ Response 200 (application/vnd.api+json)

        :[](response/anime/get-all-200.json)

## Update [PATCH]

+ Response 200 (application/vnd.api+json)

## Create [POST]

+ Response 200 (application/vnd.api+json)

## Delete [DELETE]

+ Response 200 (application/vnd.api+json)
