# Authentication [/todo3]

Kitsu uses OAuth 2 for authentication. It is not required to send authenticated requests for most endpoints.

After registering your app, you will receieve a client ID and a client secret. The client ID is considered public information and is used to build login URLs or included in source code. The client secret **must** be kept confidential.

**NOTE:** Application registration has not yet been implemented, so for now all requests should be  made with the following client ID and client secret:

```
CLIENT_ID: dd031b32d2f56c990b1425efe6c42ad847e7fe3ab46bf1299f05ecd856bdb7dd
CLIENT_SECRET: 54d7307928f63414defd96399fc31ba847961ceaecef3a5fd93144e960c0e151
```

## Grant Types

OAuth 2 provides several grant types for different use cases. The grant types defined are:

- **Authorisation Code** for apps running on a web server, browser-based and and mobile apps
- **Password** for logging in with a username and Password
- **Client Credentials** for application access

+ Parameters
  + id (string) ... An ID

+ Model
  + Body
    ```
    :[](authentication.json)
    ```

## Request Access Token [POST]

A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.

+ Response 200

## Revoke Access Token [GET]

I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.

+ Response 200
