# Group Characters & People

:[](models/characters-people/anime-characters.apib)
:[](models/characters-people/anime-productions.apib)
:[](models/characters-people/anime-staff.apib)
:[](models/characters-people/castings.apib)
:[](models/characters-people/characters.apib)
:[](models/characters-people/manga-characters.apib)
:[](models/characters-people/manga-staff.apib)
:[](models/characters-people/people.apib)
:[](models/characters-people/producers.apib)
