# Data Structures

:[](characters-people/anime-characters.mson)
:[](characters-people/anime-productions.mson)
:[](characters-people/anime-staff.mson)
:[](characters-people/castings.mson)
:[](characters-people/characters.mson)
:[](characters-people/manga-characters.mson)
:[](characters-people/manga-staff.mson)
:[](characters-people/people.mson)
:[](characters-people/producers.mson)

:[](groups/group-categories.mson)
:[](groups/group-members.mson)
:[](groups/group-neighbors.mson)
:[](groups/groups.mson)

:[](media/anime.mson)
:[](media/categories.mson)
:[](media/chapters.mson)
:[](media/drama.mson)
:[](media/episodes.mson)
:[](media/franchises.mson)
:[](media/genres.mson)
:[](media/installments.mson)
:[](media/manga.mson)
:[](media/mappings.mson)
:[](media/media-relationships.mson)
:[](media/streamers.mson)
:[](media/streaming-links.mson)

:[](posts/comment-likes.mson)
:[](posts/comments.mson)
:[](posts/post-likes.mson)
:[](posts/posts.mson)

:[](reviews/review-likes.mson)
:[](reviews/reviews.mson)

:[](site-announcements/site-announcements.mson)

:[](users/favorites.mson)
:[](users/follows.mson)
:[](users/library-entries.mson)
:[](users/profile-link-sites.mson)
:[](users/profile-links.mson)
:[](users/roles.mson)
:[](users/stats.mson)
:[](users/user-roles.mson)
:[](users/users.mson)
