FORMAT: 1A
HOST: https://kitsu.io/api/edge

# Kitsu API

Kitsu is a modern anime discovery platform that helps you track the
anime you're watching, discover new anime and socialize with other
fans.

With the Kitsu API you can do everything the client can do and much
more.

API path: `https://kitsu.io/api/edge`

:[](introduction/versioning.apib)
:[](introduction/json-api.apib)
:[](introduction/http-methods.apib)
:[](introduction/status-codes.apib)
:[](introduction/tutorials.apib)
:[](introduction/questions.apib)

# Group Authentication

:[](authentication.apib)

# Group Characters & People

:[](characters-people/anime-characters.apib)
:[](characters-people/anime-productions.apib)
:[](characters-people/anime-staff.apib)
:[](characters-people/castings.apib)
:[](characters-people/characters.apib)
:[](characters-people/manga-characters.apib)
:[](characters-people/manga-staff.apib)
:[](characters-people/people.apib)
:[](characters-people/producers.apib)

# Group Groups

:[](groups/group-action-logs.apib)
:[](groups/group-bans.apib)
:[](groups/group-categories.apib)
:[](groups/group-invites.apib)
:[](groups/group-member-notes.apib)
:[](groups/group-members.apib)
:[](groups/group-neighbors.apib)
:[](groups/group-permissions.apib)
:[](groups/group-reports.apib)
:[](groups/group-ticket-messages.apib)
:[](groups/group-tickets.apib)
:[](groups/groups.apib)
:[](groups/leader-chat-messages.apib)

# Group Media

:[](media/anime.apib)
:[](media/categories.apib)
:[](media/category-favorites.apib)
:[](media/category-recommendations.apib)
:[](media/chapters.apib)
:[](media/drama.apib)
:[](media/episodes.apib)
:[](media/franchises.apib)
:[](media/genres.apib)
:[](media/installments.apib)
:[](media/manga.apib)
:[](media/mappings.apib)
:[](media/media-attribute-votes.apib)
:[](media/media-attributes.apib)
:[](media/media-follows.apib)
:[](media/media-relationships.apib)
:[](media/streamers.apib)
:[](media/streaming-links.apib)

# Group Posts

:[](posts/comment-likes.apib)
:[](posts/comments.apib)
:[](posts/post-likes.apib)
:[](posts/post-follows.apib)
:[](posts/posts.apib)
:[](posts/reports.apib)

# Group Reactions

:[](reactions/media-reaction-votes.apib)
:[](reactions/media-reactions.apib)
:[](reactions/review-likes.apib)
:[](reactions/reviews.apib)

# Group Site Announcements

:[](site-announcements/site-announcements.apib)

# Group User Libraries

:[](user-libraries/library-entries.apib)
:[](user-libraries/library-entry-logs.apib)
:[](user-libraries/library-events.apib)
:[](user-libraries/list-imports.apib)

# Group Users

:[](users/blocks.apib)
:[](users/favorites.apib)
:[](users/follows.apib)
:[](users/linked-accounts.apib)
:[](users/profile-link-sites.apib)
:[](users/profile-links.apib)
:[](users/roles.apib)
:[](users/stats.apib)
:[](users/user-roles.apib)
:[](users/users.apib)

:[](data-structures.apib)
