FORMAT: 1A
HOST: https://kitsu.io/api/edge

# Kitsu API Docs

Kitsu is a modern anime discovery platform that helps you track the
anime you're watching, discover new anime and socialize with other
fans.

With the Kitsu API you can do everything the client can do and much
more.

API path: `https://kitsu.io/api/edge`

:[](introduction/versioning.apib)
:[](introduction/json-api.apib)
:[](introduction/http-methods.apib)
:[](introduction/status-codes.apib)
:[](introduction/tutorials.apib)
:[](introduction/questions.apib)

# Group Authentication

:[](authentication.apib)

# Group Anime

:[](media/anime.apib)
:[](media/episodes.apib)
:[](media/trending-anime.apib)

# Group Manga

:[](media/manga.apib)
:[](media/chapters.apib)
:[](media/trending-manga.apib)

# Group Media Relations

:[](media/media-relationships.apib)
:[](media/mappings.apib)
:[](media/franchises.apib)
:[](media/installments.apib)

:[](media/media-attributes.apib)
:[](media/media-attribute-votes.apib)
:[](media/media-follows.apib)

# Group Categories 

:[](media/categories.apib)
:[](media/category-favorites.apib)
:[](media/category-recommendations.apib)

# Group Streamers

:[](media/streamers.apib)
:[](media/streaming-links.apib)

# Group Users

:[](users/blocks.apib)
:[](users/favorites.apib)
:[](users/follows.apib)
:[](users/linked-accounts.apib)
:[](users/profile-link-sites.apib)
:[](users/profile-links.apib)
:[](users/roles.apib)
:[](users/stats.apib)
:[](users/user-roles.apib)
:[](users/users.apib)

# Group User Libraries

:[](user-libraries/library-entries.apib)
:[](user-libraries/library-entry-logs.apib)
:[](user-libraries/library-events.apib)
:[](user-libraries/list-imports.apib)

# Group Reactions

:[](reactions/media-reaction-votes.apib)
:[](reactions/media-reactions.apib)

:[](reactions/review-likes.apib)
:[](reactions/reviews.apib)

# Group Posts

:[](posts/posts.apib)
:[](posts/post-likes.apib)
:[](posts/post-follows.apib)

# Group Comments

:[](posts/comments.apib)
:[](posts/comment-likes.apib)

# Group Characters

:[](characters-people/anime-characters.apib)
:[](characters-people/manga-characters.apib)
:[](characters-people/characters.apib)

# Group Producers & Staff

:[](characters-people/anime-productions.apib)
:[](characters-people/anime-staff.apib)
:[](characters-people/manga-staff.apib)

:[](characters-people/producers.apib)
:[](characters-people/people.apib)

:[](characters-people/castings.apib)

# Group Groups

:[](groups/groups.apib)
:[](groups/group-action-logs.apib)
:[](groups/group-bans.apib)
:[](groups/group-categories.apib)
:[](groups/group-invites.apib)
:[](groups/group-member-notes.apib)
:[](groups/group-members.apib)
:[](groups/group-neighbors.apib)
:[](groups/group-permissions.apib)
:[](groups/group-reports.apib)
:[](groups/group-ticket-messages.apib)
:[](groups/group-tickets.apib)
:[](groups/leader-chat-messages.apib)

# Group Reports

:[](posts/reports.apib)

# Group Site Announcements

:[](site-announcements/site-announcements.apib)

:[](data-structures.apib)
