# Library [/library-entries]

TBA

## Add Library Entries [POST]

+ Response 200

## Delete Library Entries [DELETE]

+ Response 200

## Get Library Entries [GET]

+ Response 200

## Update Library Entries [PATCH]

+ Response 200
