# Group Media

:[](media/anime.apib)
:[](media/categories.apib)
:[](media/category-favorites.apib)
:[](media/category-recommendations.apib)
:[](media/chapters.apib)
:[](media/drama.apib)
:[](media/episodes.apib)
:[](media/franchises.apib)
:[](media/genres.apib)
:[](media/installments.apib)
:[](media/manga.apib)
:[](media/mappings.apib)
:[](media/media-attribute-votes.apib)
:[](media/media-attributes.apib)
:[](media/media-follow.apib)
:[](media/media-reaction-votes.apib)
:[](media/media-reactions.apib)
:[](media/media-relationships.apib)
:[](media/streamers.apib)
:[](media/streaming-links.apib)
