## Post Follows [/post-follows/{id}]

+ Parameters
    + id (number, `3`) - ID of the post follow resource

+ Attributes (postFollowsAttributes)

### GET List [GET /post-follows]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (postFollows)
        + meta (object, required)
            + count: 2076 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/post-follows?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/post-follows?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/post-follows?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/post-follows?page%5Blimit%5D=10&page%5Boffset%5D=2066` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (postFollowsAttributes)

+ Response 404 (application/vnd.api+json)
    + Attributes (error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)
