## Profile Links [/profile-links/{id}]

+ Parameters
    + id (number, `1`) - ID of the profile link resource

+ Attributes (profileLinksAttributes)

### Fetch Collection [GET /profile-links]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (profileLinks)
        + meta (object, required)
            + count: 11465 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/profile-links?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/profile-links?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/profile-links?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/profile-links?page%5Blimit%5D=10&page%5Boffset%5D=11455` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (profileLinks)

+ Response 404 (application/vnd.api+json)
    + Attributes (error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)
