## Anime Characters [/anime-characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime character resource

+ Attributes (animeCharactersAttributes)

### Fetch Collection [GET /anime-characters]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (animeCharacters)
        + meta (object, required)
            + count: 109379 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=109369` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

### Fetch Resource [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeCharacters)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Create Resource [POST]

+ Request (application/vnd.api+json)

+ Response 201 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Update Resource [PATCH]

+ Request (application/vnd.api+json)

+ Response 200 (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 403 (application/vnd.api+json)
    + Attributes (Error403)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 409 (application/vnd.api+json)
    + Attributes (Error409)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)

### Delete Resource [DELETE]

+ Request (application/vnd.api+json)

+ Response 202 (application/vnd.api+json)

+ Response 204 (application/vnd.api+json)

+ Response 400 (application/vnd.api+json)
    + Attributes (Error400)

+ Response 401 (application/vnd.api+json)
    + Attributes (Error401)

+ Response 404 (application/vnd.api+json)
    + Attributes (Error404)

+ Response 500 (application/vnd.api+json)
    + Attributes (Error500)
