## Anime Staff [/anime-staff/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime staff resource

+ Attributes (animeStaffAttributes)

### GET List [GET /anime-staff]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeStaff)
        + meta (object)
            + count: 88543 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=88533`

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid page value
                + detail: 0 is not a valid value for limit page parameter.
                + code: 118
                + status: 400

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeStaff)

+ Response 404 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Record not found
                + detail: The record identified by 0 could not be found.
                + code: 404
                + status: 404

+ Response 400 (application/vnd.api+json)
    + Attributes
        + errors (array)
            + (object)
                + title: Invalid field value
                + detail: helloworld is not a valid value for id.
                + code: 103
                + status: 400
