## Anime Productions [/anime-productions/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime production resource

+ Attributes (animeProductionsAttributes)

### GET List [GET /anime-productions]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeProductions)
        + meta (object)
            + count: 28401 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-productions?page%5Blimit%5D=10&page%5Boffset%5D=28391`


### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeProductions)
