## Anime Staff [/anime-staff/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime staff resource

+ Attributes (animeStaffAttributes)

### GET List [GET /anime-staff]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeStaff)
        + meta (object)
            + count: 88543 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/anime-staff?page%5Blimit%5D=10&page%5Boffset%5D=88533`


### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeStaff)
