## Anime Characters [/anime-characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the anime character

+ Attributes (animeCharactersAttributes)

### GET List [GET /anime-characters{?page%5Blimit%5D,page%5Boffset%5D}]

+ Parameters
    + page%5Blimit%5D (optional, number, `10`)
    + page%5Boffset%5D (optional, number, `0`)

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (animeCharacters)
        + meta (object)
            + count: 109379 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=0` (string)
            + next: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=10` (string)
            + last: `https://kitsu.io/api/edge/anime-characters?page%5Blimit%5D=10&page%5Boffset%5D=109369` (string)


### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (animeCharacters)
