## Castings [/castings/{id}]

+ Parameters
    + id (number, `1`) - ID of the casting resource

+ Attributes (castingsAttributes)

### GET List [GET /castings]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (castings)
        + meta (object)
            + count: 244549 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/castings?page%5Blimit%5D=10&page%5Boffset%5D=244539`


### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (castings)
