## Characters [/characters/{id}]

+ Parameters
    + id (number, `1`) - ID of the character resource

+ Attributes (charactersAttributes)

### GET List [GET /characters]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (characters)
        + meta (object, required)
            + count: 950090 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/characters?page%5Blimit%5D=10&page%5Boffset%5D=94999` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (errors400)

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (characters)

+ Response 404 (application/vnd.api+json)
    + Attributes (errors404)

+ Response 400 (application/vnd.api+json)
    + Attributes (errors400)
