## Manga Staff [/manga-staff/{id}]

+ Parameters
    + id (number, `1`) - ID of the manga staff resource

+ Attributes (mangaStaffAttributes)

### GET List [GET /manga-staff]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array, required)
            + (mangaStaff)
        + meta (object, required)
            + count: 1 (number, required)
        + links (object, required)
            + first: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)
            + prev: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=0` - Omitted if on first page
            + next: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=10` - Omitted if on last page
            + last: `https://kitsu.io/api/edge/manga-staff?page%5Blimit%5D=10&page%5Boffset%5D=0` (required)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)

### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (mangaStaff)

+ Response 404 (application/vnd.api+json)
    + Attributes (error404)

+ Response 400 (application/vnd.api+json)
    + Attributes (error400)
