## People [/people/{id}]

+ Parameters
    + id (number, `1`) - ID of the person resource

+ Attributes (peopleAttributes)

### GET List [GET /people]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (array)
            + (people)
        + meta (object)
            + count: 27957 (number)
        + links (object)
            + first: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=0`
            + next: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=10`
            + last: `https://kitsu.io/api/edge/people?page%5Blimit%5D=10&page%5Boffset%5D=27947`


### GET Single [GET]

+ Response 200 (application/vnd.api+json)
    + Attributes
        + data (people)
