# List [/anime]

TBA

## Fetch [GET]

+ Request
    + Headers

            :[](../../header/jsonapi.apib)

+ Response 200 (application/vnd.api+json)

        :[](response/fetch-list-200.json)

## Update [PATCH]

+ Response 200 (application/vnd.api+json)

## Create [POST]

+ Response 200 (application/vnd.api+json)

## Delete [DELETE]

+ Response 200 (application/vnd.api+json)
