## Single [/anime/{id}]

TBA

+ Parameters
    + id (number) - ID of the anime

### Fetch [GET]

+ Request
    + Headers

            :[](../../header/jsonapi.apib)

+ Response 200 (application/vnd.api+json)

        :[](response/fetch-single-200.json)
